### ISSUE TITLE
Sprint 6 Requirements

### ISSUE THREAD

**Issue by juliusBam** [Grossstadt-Pinguine/SWKOM_Paperless#67]
# Sprint 6
In the sprint 6 we have to implement the connection with elasticsearch and kibana. The demo application can be found at: https://git.technikum-wien.at/swen/swen3/java/paperlessservices/-/blob/elasticsearch

## TODO
1. Use the docker.-compose.yaml file from the demo to setup the services, found at: https://git.technikum-wien.at/swen/swen3/java/paperlessservices/-/blob/elasticsearch/docker-compose.yml
2. Add an elasticsearch config to the java project in paperlessOCR
3. Kibana has to be configured to "find" the elasticsearch service --> done in the UI at port 5601
4. You will be asked to insert the verification code from the kibana server --> docker exec to execute command in container: `sudo docker exec -it paperlessservices-kibanba-1 bash`
5. Command is "kibana-verification-code" --> returns the code you need
6. In Java paperlessOCR you have to add an elasticSearchService which will use the elasticsearch client (provided by a library)
7. The service should add a document to the created index when a document is updated and/or uploaded
8. For the upload of a new document we can use a put with a not existing id (using the id from the db would be ingenious) so that we can manually set the id to be the same as in the db (no need to update the db table with the info once it is done)
9. Add config for elastic search and its service also in the paperlessREST application --> will be needed for the search function by the FE

### Java elasticSearch API --> ElasticSearchClient
1. Dependency:
```xml
        <dependency>
            <groupId>co.elastic.clients</groupId>
            <artifactId>elasticsearch-java</artifactId>
            <version>8.9.0</version>
        </dependency>
```
2. Create a configuration for the elasticSearch instance --> required for the index naming and the connection with the server (used to instantiate the client). It is important that this contains a Bean of type ElasticsearchClient:
![image](https://github.com/Grossstadt-Pinguine/SWKOM_Paperless/assets/80284467/86baac3b-1e0f-416b-aad3-f3ce1c39500d)
3. The attribute ".document" is used to insert the content of the request, meaning that we can just place the JSON string we want to save (with the desired fields) as a parameter:
![image](https://github.com/Grossstadt-Pinguine/SWKOM_Paperless/assets/80284467/84639a4e-bb9d-4e28-b466-e065dffcf12e)

### Low level request to elastic_search --> we will not do this, rather we will use the elasticSearchClient
1. Get data by id: `GET /myindex/_doc/$id`
2. Put document: `PUT /myindex/_doc/$id {$content in JSON}`
4. Post document: `POST /myindex/_doc {$content in JSON}`
5. Get all --> you need a search query: 
```
GET /myindex/_search 
{
  "query": {
    "match_all": {}
  }
}
```
6. Delete doc by id: `DELETE /myindex/_doc/$id`
10. Search with matches: 
```
GET /myindex/_search 
{
  "query": {
    "match": {
      "hello": "hello" //key is the field, value is the value to be matched
    }
  }
}
```
11. Search with wildcard:
```
GET /myindex/_search 
{
  "query": {
    "wildcard": {
      "hello": "h*"
    }
  }
}
```

### Test if kibana + elastic works
1. In the console open the burger menu and click on dev tools: 
![image](https://github.com/Grossstadt-Pinguine/SWKOM_Paperless/assets/80284467/900dcafb-f299-46d3-8248-46259242d73b)
2. Define an endpoint in the console in the devtools: --> used to test what happens
![image](https://github.com/Grossstadt-Pinguine/SWKOM_Paperless/assets/80284467/55a4afd9-4d95-47da-9b56-6d5c16a5b177)
4. Data is sent to kibana via simple HTTP calls (You can test it with curl)
5. You can access further documentation and export it as curl if you place the cursor in the first line of the request and clicking on the wrench: 
![image](https://github.com/Grossstadt-Pinguine/SWKOM_Paperless/assets/80284467/d3b645c4-5c97-4330-bda1-23dda126ef96)

**Comment by skyler544** [comment]
See also: the [Technikum Gitlab README for Kibana/ElasticSearch](https://git.technikum-wien.at/swen/swen3/java/paperlessservices/-/blob/elasticsearch/ELASTICSEARCH.md)
