### ISSUE TITLE
Sprint 7

### ISSUE THREAD

**Issue by juliusBam** [Grossstadt-Pinguine/SWKOM_Paperless#71]
# Sprint 7

In sprint 7 the project should be finalized, meaning:
- Some code cleanup (e.g. https://github.com/Grossstadt-Pinguine/SWKOM_Paperless/issues/68 and https://github.com/Grossstadt-Pinguine/SWKOM_Paperless/issues/60 )
- An additional use case should be implemented: delete documents sounds perfect and easy to implement
- Integration tests should be added for the desired use cases: upload, delete, get 

## Integration tests
The integration tests should not be performed upon the "package" operation, rather in the "verifiy" step. For integration tests it is necessary to start the other nodes, in order to use the real services. Therefore the docker network has to be started before the tests can be performed (docker compose up should be runned in the "package" step). Another option would be to create a script and trigger it when the "verify" step starts --> more complicated to evaluate the results.

## Helpful links

https://www.baeldung.com/spring-boot-testing
https://www.mojohaus.org/build-helper-maven-plugin/usage.html
https://www.baeldung.com/maven-profiles

**Comment by skyler544** [comment]
Our plan for integration tests:

* Build a separate application for integration testing
* Open up a way for the integration tester to find out if the REST backend is ready
* Test the application functionality
  Pseudocode:
  ```
rest_server_not_ready = true
  while (rest_server_not_ready)
    if (check(healthcheck endpoint))
       rest_server_not_ready = false

run document upload integration test

run search document integration test

run change document content integration test (or delete document)

if (all tests successful) 
  exit 0
else 
  exit 1, 2, 3 (whichever test failed)
```
```
